global:  
  scrape_interval:     5s
  evaluation_interval: 5s
 
scrape_configs:  
  - job_name: 'customer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8280']
      
  - job_name: 'preference'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8180']
      
  - job_name: 'recommendation'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']